### ISSUE TITLE
TypeError: Can't instantiate abstract class LitInteraction with abstract methods forward

### ISSUE THREAD

**Issue by HUSTLDL** [Sirui-Xu/InterDiff#4]
I have completed the data preparation process, and I want to use your provided model to evaluate short-term generation on the BEHAVE  dataset. But I encountered a problem which is "TypeError: Can't instantiate abstract class LitInteraction with abstract methods forward", and I haven't figure it out. Some detailed information is as follows:

```
$python eval_smpl_short.py --resume_checkpoint checkpoints/diffusion.ckpt --resume_checkpoint_obj checkpoints/correction.ckpt
{'MOTION_PATH': './data/behave/sequences', 'OBJECT_TEMPLATE': './data/behave/objects', 'SPLIT_PATH': './data/behave/split.json', 'MODEL_PATH': './data/behave/mano_v1_2/models'}
/home/name/.conda/envs/interdiff/lib/python3.8/site-packages/pointnet2_ops/pointnet2_utils.py:15: UserWarning: Unable to load pointnet2_ops cpp extension. JIT Compiling.
  warnings.warn("Unable to load pointnet2_ops cpp extension. JIT Compiling.")
NVIDIA GeForce RTX 2080
85it [01:06,  1.29it/s]
====> The number of clips for test data: 3602 <====
dataset loaded
Traceback (most recent call last):
  File "eval_smpl_short.py", line 425, in <module>
    model = LitInteraction.load_from_checkpoint(args.resume_checkpoint, args=args).to(device)
  File "/home/name/.conda/envs/interdiff/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 169, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, *args, **kwargs)
  File "/home/name/.conda/envs/interdiff/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model = cls(*cls_args, **cls_kwargs)
TypeError: Can't instantiate abstract class LitInteraction with abstract methods forward
```

**Comment by Sirui-Xu** [comment]
Hi,

The code works fine on our machine. I found that this might help (https://github.com/Lightning-AI/lightning/issues/3101). Could you try to replace every _common_step / self._common_step function to forward / self.forward in all training codes?

Best

**Comment by HUSTLDL** [comment]
It works, thank you so much!
